apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Source"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-volume-claim
spec:
  storageClassName: manual
  volumeName: app-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi