apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /intenteditor
        pathType: Prefix
        backend:
          service:
            name: intenteditor
            port:
              number: 80
      - path: /qaeditor
        pathType: Prefix
        backend:
          service:
            name: qaeditor
            port:
              number: 80
      - path: /qaservice
        pathType: Prefix
        backend:
          service:
            name: qaservice
            port:
              number: 80
      - path: /intentclassifier
        pathType: Prefix
        backend:
          service:
            name: intentclassifier
            port:
              number: 80
      