apiVersion: v1
kind: Service
metadata:
  name: {{ lower .Values.serviceName }}
spec:
  selector:
    app: {{ lower .Values.serviceName }}
  ports:
    - name: main
      protocol: TCP
      port: 80
      targetPort: 80
    - name: debug
      protocol: TCP
      port: 9229
      targetPort: 9229