apiVersion: v1
kind: Pod
metadata:
 name: win-tests
 labels:
   app: win-tests
spec:
  volumes:
  - name: app-storage
    persistentVolumeClaim:
      claimName: app-volume-claim
  containers:
  - name: dotnet-tests
    image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: win-tests
spec:
  selector:
    app: win-tests
  ports:
    - name: main
      protocol: TCP
      port: 80
      targetPort: 80